[project]
name = "inctxt"
version = "0.0.1"
authors = [
  { name = "Akash Gupta", email = "guptaalgebra@gmail.com" },
  { name = "Ivaxi Sheth" },
  { name = "Vyas Raina" },
]
dependencies = [
  "torch",
  "transformers",
  "datasets",
  "mypy",
  "python-dotenv",
  "rouge_score",
]
